check

diff --git a/.github/workflows/playwright.yml b/.github/workflows/playwright.yml
--- a/.github/workflows/playwright.yml
+++ b/.github/workflows/playwright.yml
@@ -33,13 +33,13 @@ jobs:
     strategy:
       matrix:
         shard: [1, 2, 3, 4]
-    outputs:
-      shard_1: ${{ steps.shard-result.outputs.shard_1 }}
-      shard_2: ${{ steps.shard-result.outputs.shard_2 }}
-      shard_3: ${{ steps.shard-result.outputs.shard_3 }}
-      shard_4: ${{ steps.shard-result.outputs.shard_4 }}
-      shard_outputs: ${{ steps.shard-result.outputs }}
-      all_passed: ${{ !contains(toJSON(steps.shard-result.outputs), 'failure') }}
+    # outputs:
+    #   shard_1: ${{ steps.shard-result.outputs.shard_1 }}
+    #   shard_2: ${{ steps.shard-result.outputs.shard_2 }}
+    #   shard_3: ${{ steps.shard-result.outputs.shard_3 }}
+    #   shard_4: ${{ steps.shard-result.outputs.shard_4 }}
+    #   shard_outputs: ${{ steps.shard-result.outputs }}
+    #   all_passed: ${{ !contains(toJSON(steps.shard-result.outputs), 'failure') }}
     name: 'Playwright Test (Shard ${{ matrix.shard }}/4)'
     runs-on: ubuntu-latest
     steps:
@@ -54,13 +54,13 @@ jobs:
     - name: Run Playwright tests
       id: shard-run
       run: npx playwright test --shard=${{ matrix.shard }}/4
-    - name: Output Plawright Results
-      if: always()
-      id: shard-result
-      run: |
-        echo "steps.shard-run.conclusion=${{ steps.shard-run.conclusion }}"
-        echo "steps.shard-run.outcome=${{ steps.shard-run.outcome }}"
-        echo "shard_${{ matrix.shard }}=${{ steps.shard-run.conclusion }}" >> "$GITHUB_OUTPUT"
+    # - name: Output Plawright Results
+    #   if: always()
+    #   id: shard-result
+    #   run: |
+    #     echo "steps.shard-run.conclusion=${{ steps.shard-run.conclusion }}"
+    #     echo "steps.shard-run.outcome=${{ steps.shard-run.outcome }}"
+    #     echo "shard_${{ matrix.shard }}=${{ steps.shard-run.conclusion }}" >> "$GITHUB_OUTPUT"
   test-summary:
     name: Playwright Tests Summary
     needs: [test, test-conditionals]
@@ -68,29 +68,34 @@ jobs:
     if: always()
     steps:
       - name: Print everything
+        # run: |
+        #   echo "needs.test-conditionals.outputs.should-run=${{ needs.test-conditionals.outputs.should-run }}"
+        #   echo "needs.test.outputs.shard_1=${{ needs.test.outputs.shard_1 }}"
+        #   echo "needs.test.outputs.shard_2=${{ needs.test.outputs.shard_2 }}"
+        #   echo "needs.test.outputs.shard_3=${{ needs.test.outputs.shard_3 }}"
+        #   echo "needs.test.outputs.shard_4=${{ needs.test.outputs.shard_4 }}"
+        #   echo "needs.test.outputs.shard_outputs=${{ needs.test.outputs.shard_outputs }}"
+        #   echo "needs.test.outputs.all_passed=${{ needs.test.outputs.all_passed }}"
+        #   echo "needs.test.result=${{ needs.test.result }}"
+        #   echo "needs.*.result=${{ toJSON(needs.*.result) }}"
+        #   echo "contains(needs.*.result, 'failure')=${{ contains(needs.*.result, 'failure') }}"
         run: |
           echo "needs.test-conditionals.outputs.should-run=${{ needs.test-conditionals.outputs.should-run }}"
-          echo "needs.test.outputs.shard_1=${{ needs.test.outputs.shard_1 }}"
-          echo "needs.test.outputs.shard_2=${{ needs.test.outputs.shard_2 }}"
-          echo "needs.test.outputs.shard_3=${{ needs.test.outputs.shard_3 }}"
-          echo "needs.test.outputs.shard_4=${{ needs.test.outputs.shard_4 }}"
-          echo "needs.test.outputs.shard_outputs=${{ needs.test.outputs.shard_outputs }}"
-          echo "needs.test.outputs.all_passed=${{ needs.test.outputs.all_passed }}"
           echo "needs.test.result=${{ needs.test.result }}"
-          echo "needs.*.result=${{ toJSON(needs.*.result) }}"
-          echo "contains(needs.*.result, 'failure')=${{ contains(needs.*.result, 'failure') }}"
-      - name: Check test matrix status
-        if: needs.test-conditionals.outputs.should-run == 'true' && needs.test.result != 'success'
+      # - name: Check Playwright Tests
+      #   if: needs.test-conditionals.outputs.should-run != 'true'
+      #   run: |
+      #     echo "Tests were skipped"
+      #     exit 0
+      - name: Check for failed tests
         run: |
-          echo "Some Playwright tests failed"
-          exit 1
-      - name: Tests passed
-        if: needs.test-conditionals.outputs.should-run == 'true' && needs.test.outputs.all_passed == 'true'
-        run: |
-          echo "Tests passed"
-          exit 0
-      - name: Tests skipped
-        if: needs.test-conditionals.outputs.should-run != 'true'
-        run: |
-          echo "Tests were skipped"
-          exit 0
+          if [[ needs.test-conditionals.outputs.should-run != 'true' ]]; then
+            echo "Playwright tests were skipped"
+            exit 0
+          elif [[ needs.test.result != 'success' ]]; then
+            echo "Some tests failed"
+            exit 1
+          else
+            echo "All tests passed or were skipped"
+            exit 0
+          fi
